# This is a basic workflow to help you get started with Actions

name: Build PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: LaTeX compilation
        uses: xu-cheng/latex-action@v2
        with:
          root_file: CV.tex
      
      - name: Update PDF in repository
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automatically updating PDF in repository"
          add: CV.pdf
